"""Stage 05 — Promotional uplift (Challenge C).

    uv run scripts/05_uplift.py

Output: reports/05_uplift.md
"""

from __future__ import annotations

import argparse

import pandas as pd

from analysis import cleaning, config, economics, io, plotting, uplift
from analysis.reporting import MarkdownReport


def main(min_weeks: int = 3, pre_weeks: int = 6, post_weeks: int = 6) -> None:
    raw = io.load_raw_transactions()
    flagged, _ = cleaning.flag_records(raw)
    rates = economics.sku_margin_rates(flagged)

    panel = pd.read_parquet(config.PROCESSED_DIR / "weekly_sku_panel.parquet")
    panel = panel[panel["is_complete_week"]].copy()
    panel["week_start"] = pd.to_datetime(panel["week_start"])

    report = MarkdownReport(
        title="Stage 05 — Promotional uplift (Challenge C)",
        stage="scripts/05_uplift.py",
        subtitle=(
            "Incremental units generated by past promotional episodes, with an explicit "
            "counterfactual, a post-promotion check, and a margin verdict."
        ),
    )

    # ------------------------------------------------------------- approach
    report.heading("1. How incrementality is identified")
    report.text(
        "Episodes are derived from observed promotional intensity — contiguous runs of "
        "weeks where more than half of a SKU's units sold under a combo — rather than "
        "from combo identifiers. Several combos overlap on the same SKU, and what the "
        "business actually ran is the combined pressure, not any single code."
    )
    report.bullets([
        "**Baseline**: median weekly units over the six preceding weeks, restricted to "
        "weeks that were themselves quiet (under 20% promoted). A contaminated baseline "
        "would compare a promotion against another promotion.",
        "**Difference-in-differences**: the baseline is scaled by how much SKUs *not* "
        "promoted in the same weeks moved between the two windows. This absorbs "
        "market-wide shifts — seasonality, a strong month, a distribution push — that a "
        "raw before/after comparison would credit to the promotion.",
        "**Post-promotion window**: six weeks after. Volume that is repaid by a slump "
        "afterwards was pulled forward, not created. Net uplift subtracts it.",
    ])
    report.note(
        "The difference-in-differences estimate assumes the control SKUs would have moved "
        "in parallel with the promoted one absent the promotion. With six SKUs across "
        "three categories that assumption is doing real work and cannot be tested "
        "directly. Where the two estimates diverge sharply, the divergence itself is the "
        "finding — it means the answer depends on an assumption the data cannot settle."
    )

    # ------------------------------------------------------------ episodes
    all_episodes = pd.concat(
        [
            uplift.detect_episodes(panel, code, min_weeks)
            for code in sorted(panel["product_code"].unique())
        ],
        ignore_index=True,
    )
    # A clean baseline is required; a post-window is not. Episodes still running
    # at the end of the extract are the most recent decisions the commercial team
    # made, and excluding them would drop the best-identified events in the data
    # — the two SKUs that went 14 months with no promotion at all. Their
    # pull-forward simply cannot be checked yet, and the table says so.
    usable = all_episodes[all_episodes["weeks_before_available"].ge(4)].copy()

    report.heading("2. Promotional episodes detected")
    report.key_values({
        "Episodes of 3+ promoted weeks": len(all_episodes),
        "With enough preceding weeks to establish a baseline": len(usable),
        "Of those, still running at the end of the extract": int(
            usable["weeks_after_available"].eq(0).sum()
        ),
    })
    report.table(
        all_episodes[[
            "product_code", "start_week", "end_week", "n_weeks", "units",
            "mean_promo_share", "mean_discount_depth",
            "weeks_before_available", "weeks_after_available",
        ]]
    )

    # ------------------------------------------------------------ estimates
    results = []
    for _, episode in usable.iterrows():
        result = uplift.estimate_uplift(panel, episode["product_code"], episode,
                                        pre_weeks, post_weeks)
        margin_rate = economics.margin_rate_for(rates, episode["product_code"])
        result |= uplift.promotion_economics(result, margin_rate)
        results.append(result)

    estimates = pd.DataFrame(results)

    # How much weight each estimate deserves, scored on the three things that can
    # invalidate it. The recommendation is drawn from well-identified episodes,
    # not simply from the largest number in the table.
    credibility = (
        estimates["baseline_is_clean"].astype(int)
        + estimates["control_skus"].ne("none available").astype(int)
        + estimates["post_weeks"].gt(0).astype(int)
    )
    estimates["evidence"] = credibility.map({3: "strong", 2: "moderate", 1: "weak", 0: "weak"})
    estimates["_rank"] = credibility
    estimates = estimates.sort_values(
        ["net_uplift_units"], ascending=False
    ).reset_index(drop=True)

    report.heading("3. Uplift estimates")
    report.table(estimates[[
        "product_code", "start_week", "n_weeks", "mean_discount_depth",
        "baseline_units_per_week", "baseline_is_clean", "actual_units",
        "uplift_naive_%", "control_skus", "control_factor", "uplift_did_%",
        "post_weeks", "post_delta_units", "net_uplift_units", "pulled_forward",
    ]])
    report.note(
        "`uplift_naive_%` is the raw before/after comparison; `uplift_did_%` corrects it "
        "for what non-promoted SKUs did over the same weeks. Three columns decide how much "
        "weight an estimate deserves:\n"
        "\n"
        "- `control_skus` — when it reads *none available*, every other SKU was itself "
        "promoted in those weeks, the difference-in-differences correction collapses to "
        "1.0, and the estimate is really just the naive before/after comparison.\n"
        "- `baseline_is_clean` — false means the preceding weeks were themselves promoted, "
        "so the promotion is being compared against another promotion.\n"
        "- `post_weeks` — zero means the episode was still running when the extract ended, "
        "so pull-forward could not be checked in either direction."
    )

    report.heading("4. Was the volume worth the discount?")
    report.text(
        "Incremental margin counts only the units the promotion created. The discount, "
        "however, is paid on *every* unit sold in the window — including the ones that "
        "would have sold anyway. That asymmetry is what makes deep discounts on "
        "already-selling products destroy value even when uplift is positive."
    )
    report.table(estimates[[
        "product_code", "start_week", "mean_discount_depth", "avg_net_price",
        "unit_cost_assumed", "margin_per_unit_at_promo_price", "incremental_units",
        "incremental_margin", "discount_subsidy_on_baseline_units",
        "net_margin_effect", "evidence", "verdict",
    ]])
    report.note(
        "**The pattern in this table is the headline.** The episodes that create margin "
        "are the ones with a discount depth near zero — promotional placement, bundling "
        "or visibility without a price cut — while every episode with a double-digit "
        "discount destroys margin, including some with genuinely positive volume uplift. "
        "The volume was real; it just cost more to buy than it returned."
    )
    report.note(
        "**A confound worth naming.** Several episodes on SKU 1283 fall in its natural "
        "February–April peak, and for those weeks no clean control SKU exists, so the "
        "difference-in-differences correction collapses and the estimate cannot separate "
        "the promotion from the season. Those rows are marked `weak`, and the "
        "recommendation below does not rest on them."
    )
    report.note(
        f"Unit cost uses the reconstruction from finding F-003 ({economics.ASSUMED_READING}). "
        "If VEMIO answers open question Q5 differently, the unit and revenue columns stand "
        "and every margin column moves."
    )

    # -------------------------------------------------------------- figures
    for _, row in estimates.head(2).iterrows():
        code = row["product_code"]
        series = panel[panel["product_code"].eq(code)].sort_values("week_start").copy()
        series["counterfactual"] = row["expected_units_did"] / row["n_weeks"]
        name = series["product_name"].iloc[0]
        figure = plotting.uplift_plot(
            series, (row["start_week"], row["end_week"]),
            f"{code} — {name}: promotional episode from {pd.Timestamp(row['start_week']).date()}",
            f"05_uplift_{code}_{pd.Timestamp(row['start_week']).date()}",
        )
        report.figure(
            figure,
            f"{code} ({name}): weekly units with the promotional window shaded and the "
            "difference-in-differences counterfactual overlaid. The gap between the line "
            "and the counterfactual inside the shaded band is the estimated incremental "
            "volume; what happens immediately to its right is the pull-forward check.",
        )

    # ------------------------------------------------------ recommendations
    ranked = estimates.sort_values(["_rank", "net_margin_effect"], ascending=[False, False])
    repeat = ranked[ranked["verdict"].eq("repeat")].head(1)
    drop = ranked[ranked["verdict"].eq("do not repeat")].sort_values("net_margin_effect").head(1)

    report.heading("5. Verdict")
    for label, subset in (("Repeat", repeat), ("Do not repeat", drop)):
        if subset.empty:
            report.text(f"**{label}** — no episode in this dataset qualifies.")
            continue
        row = subset.iloc[0]
        report.text(
            f"**{label}: SKU {row['product_code']}, the episode starting "
            f"{pd.Timestamp(row['start_week']).date()}** "
            f"({row['n_weeks']} weeks, average discount depth "
            f"{row['mean_discount_depth']:.1%}). It produced "
            f"{row['net_uplift_units']:,.0f} net incremental units against a "
            f"counterfactual of {row['expected_units_did']:,.0f}, worth "
            f"{row['incremental_margin']:,.0f} in incremental margin, while the discount "
            f"cost {row['discount_subsidy_on_baseline_units']:,.0f} on units that would "
            f"have sold anyway — a net margin effect of {row['net_margin_effect']:,.0f}."
            + (
                " The post-promotion weeks show no offsetting slump."
                if not row["pulled_forward"]
                else " Note the post-promotion slump: part of this volume was pulled "
                "forward rather than created."
            )
        )

    # The two SKUs that ran the same long promotion are the clearest illustration
    # of why volume uplift alone cannot decide anything.
    twins = estimates[
        estimates["product_code"].isin(["1665", "1875"]) & estimates["n_weeks"].gt(40)
    ]
    if len(twins) == 2:
        a, b = twins.iloc[0], twins.iloc[1]
        winner, loser = (a, b) if a["net_margin_effect"] > b["net_margin_effect"] else (b, a)
        report.heading("5.1 The same promotion, opposite verdicts")
        report.text(
            f"SKUs {winner['product_code']} and {loser['product_code']} ran the same "
            f"long-running promotion — both for {int(winner['n_weeks'])} weeks, both at "
            f"about {winner['mean_discount_depth']:.0%} realised discount, both selling at "
            f"almost exactly the same price ({winner['avg_net_price']:.2f} against "
            f"{loser['avg_net_price']:.2f}). Both produced large volume uplift: "
            f"{winner['net_uplift_units']:,.0f} and {loser['net_uplift_units']:,.0f} "
            f"incremental units."
        )
        report.text(
            f"Yet one made money and the other lost it: "
            f"**{winner['product_code']} nets {winner['net_margin_effect']:,.0f}** while "
            f"**{loser['product_code']} nets {loser['net_margin_effect']:,.0f}**. The "
            f"entire difference is the cost base. {winner['product_code']} carries a "
            f"{winner['margin_per_unit_at_promo_price']:.2f} margin per unit at the "
            f"promoted price; {loser['product_code']} carries "
            f"{loser['margin_per_unit_at_promo_price']:.2f} — barely half. A discount deep "
            "enough to be profitable on the first product is deeper than the second can "
            "afford."
        )
        report.note(
            "**This is the single most transferable lesson in the analysis.** Uplift is not "
            "a measure of whether a promotion worked. Two products, the same mechanic, the "
            "same response, opposite outcomes — because promotional depth has to be set "
            "against each product's own margin, not applied uniformly across a portfolio. "
            "Both of these estimates are graded `weak` on identification, so the numbers "
            "carry error bars; the direction of the contrast does not depend on them."
        )

    report.heading("6. What limits these numbers")
    report.bullets([
        "**The counterfactual is an assumption, not an observation.** There is no control "
        "group of clients who were not offered the promotion; the difference-in-differences "
        "control is other SKUs, which have their own demand drivers.",
        "**Cannibalisation is not measured.** A promotion on one shampoo may move volume "
        "from another rather than growing the category. Cross-SKU substitution during "
        "promoted weeks is the first extension worth building.",
        "**Six weeks may be too short to see the full pull-forward.** For a product bought "
        "monthly, the payback can land outside the window and make a promotion look better "
        "than it was.",
        "**Discount depth is realised, not offered.** It is inferred from gross versus net "
        "amounts, which F-004 showed reconcile only at bundle level; the true offer "
        "structure is not in the data.",
        "**Every margin figure inherits open question Q5.** Volume conclusions do not.",
    ])

    path = report.write(
        "05_uplift.md",
        params={"min_weeks": min_weeks, "pre_weeks": pre_weeks, "post_weeks": post_weeks},
    )
    estimates.to_csv(config.REPORTS_DIR / "05_uplift_estimates.csv", index=False)
    print(f"Wrote {path}")
    print(estimates[["product_code", "start_week", "net_uplift_units",
                     "net_margin_effect", "verdict"]].to_string(index=False))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--min-weeks", dest="min_weeks", type=int, default=3)
    parser.add_argument("--pre-weeks", dest="pre_weeks", type=int, default=6)
    parser.add_argument("--post-weeks", dest="post_weeks", type=int, default=6)
    main(**vars(parser.parse_args()))
